FileVersion = 1

[Project]
Name = "m3d-beef"
DefaultNamespace = "m3d"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\m3d_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\m3d.lib"]